name: Firmware

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'  # Optional: also run when version tags are pushed

jobs:
  download-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up environment
      run: |
        mkdir -p firmware_files
        echo "DOWNLOAD_DIR=$(pwd)/firmware_files" >> $GITHUB_ENV
        
    - name: Download 7z files
      run: |
        wget --recursive --level=1 --no-parent --no-directories \
          --accept "*.7z" \
          -P $DOWNLOAD_DIR \
          "https://github.com/keen-prt/keen-prt.github.io/raw/main/public/assets/files/firmware/"
          
    - name: Download zip files
      run: |
        wget --recursive --level=1 --no-parent --no-directories \
          --accept "*.zip" \
          -P $DOWNLOAD_DIR \
          "https://github.com/keen-prt/keen-prt.github.io/raw/main/public/assets/files/firmware/"
          
    - name: List downloaded files
      run: ls -la $DOWNLOAD_DIR/
      
    - name: Check if files were downloaded
      id: check_files
      run: |
        if [ $(ls -1 $DOWNLOAD_DIR/*.7z $DOWNLOAD_DIR/*.zip 2>/dev/null | wc -l) -eq 0 ]; then
          echo "No firmware files found"
          echo "files_exist=false" >> $GITHUB_OUTPUT
        else
          echo "Firmware files found"
          echo "files_exist=true" >> $GITHUB_OUTPUT
        fi
        
    - name: Create Git tag
      if: steps.check_files.outputs.files_exist == 'true'
      id: tag_version
      run: |
        # Generate timestamp-based tag
        TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
        TAG_NAME="firmware-$TIMESTAMP"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        git tag $TAG_NAME
        git push origin $TAG_NAME
        
    - name: Create Release
      if: steps.check_files.outputs.files_exist == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.tag_name }}
        name: "Firmware Release ${{ steps.tag_version.outputs.tag_name }}"
        body: |
          Automated firmware release containing all downloaded firmware files.
          
          Files included:
          - All .7z firmware archives
          - All .zip firmware archives
          
          Source: https://github.com/keen-prt/keen-prt.github.io/tree/main/public/assets/files/firmware
        draft: false
        prerelease: false
        files: |
          firmware_files/*.7z
          firmware_files/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
