name: update

on:
  workflow_dispatch:  # Manual trigger
  release:
    types: [published]  # Trigger when a new release is published

jobs:
  download-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for tags

    - name: Download files
      run: |
        mkdir -p downloads
        cd downloads
        wget -r -l1 -np -nH -N -w 2 -U "Mozilla/5.0" -e robots=off -A "*" "https://github.com/keen-prt/keen-prt.github.io/blob/main/public/assets/files/firmware/"
        cd
        ls -la downloads/
        du -h downloads/*

    - name: Create and push tag
      id: tag_version
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          VERSION="${{ github.event.release.tag_name }}"
        else
            VERSION="firmware"
        fi
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "$VERSION" -m "Release $VERSION"
        git push origin "$VERSION"
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Upload files to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.version }}
        files: |
          downloads/*.*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
